run:
  timeout: 5m
  build-tags:
    - sqlite_omit_load_extension
  go: "1.25"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gosimple
    - typecheck
    - misspell
    - goconst
    - gofmt
    - goimports
  disable:
    - depguard

linters-settings:
  errcheck:
    exclude-functions:
      - (*database/sql.Rows).Close
      - (*database/sql.Stmt).Close
      - (*database/sql.Tx).Rollback
      - (*encoding/json.Encoder).Encode
      - (net/http.ResponseWriter).Write
      - fmt.Fprintf
      - fmt.Fprint
      - fmt.Fprintln
  goimports:
    local-prefixes: jim-dot-tennis
  misspell: {}
  goconst:
    min-occurrences: 5
    ignore-strings: 'true|false|clear|error|success'

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
      text: ".*"
    - linters:
        - errcheck
      text: "InvalidateSession"
    - linters:
        - errcheck
      text: "DeleteSubscription"
