// Copyright (c) 2025-2026 James Hartt. Licensed under the MIT License.

package admin

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"jim-dot-tennis/internal/database"

	_ "github.com/mattn/go-sqlite3"
)

// Regression test for BHPLTA Rule 16 ("play down" eligibility):
//
//	"No player will be eligible to play for a team if he or she has played
//	 more than four matches in a higher team during the second half of the
//	 season."
//
// The weeks table date windows are generated by evenly dividing the season
// span across 18 weeks (~9.4 days each), so by mid-season they drift weeks
// away from the real fixture calendar. Eligibility must therefore be derived
// from the fixture's league week number (fixtures.week_id), never from the
// week date windows. This test replicates the drifted windows exactly as
// CreateSeason generates them, with fixtures on a real weekly calendar.
func TestPlayDownEligibilitySecondHalf(t *testing.T) {
	tmp := t.TempDir()
	dbPath := filepath.Join(tmp, "eligibility_test.db")

	db, err := database.New(database.Config{Driver: "sqlite3", FilePath: dbPath})
	if err != nil {
		t.Fatalf("open db: %v", err)
	}
	defer db.Close()

	if err := db.ExecuteMigrations(findMigrationsPathAdmin(t)); err != nil {
		t.Fatalf("migrate: %v", err)
	}

	ctx := context.Background()
	exec := func(query string, args ...interface{}) {
		t.Helper()
		if _, err := db.ExecContext(ctx, query, args...); err != nil {
			t.Fatalf("seed %q: %v", query, err)
		}
	}

	seasonStart := time.Date(2026, 4, 14, 0, 0, 0, 0, time.UTC)
	seasonEnd := time.Date(2026, 9, 30, 0, 0, 0, 0, time.UTC)

	exec(`INSERT INTO seasons (id, name, year, start_date, end_date, is_active) VALUES (1, '2026 Season', 2026, ?, ?, 1)`, seasonStart, seasonEnd)

	// Weeks with drifted windows, exactly as CreateSeason generates them:
	// the season span divided evenly into 18 windows (~9.4 days each).
	const numWeeks = 18
	totalDays := seasonEnd.Sub(seasonStart).Hours() / 24
	daysPerWeek := totalDays / float64(numWeeks)
	for i := 1; i <= numWeeks; i++ {
		weekStart := seasonStart.AddDate(0, 0, int(float64(i-1)*daysPerWeek))
		weekEnd := seasonStart.AddDate(0, 0, int(float64(i)*daysPerWeek)-1)
		if i == numWeeks {
			weekEnd = seasonEnd
		}
		exec(`INSERT INTO weeks (id, week_number, season_id, start_date, end_date, name) VALUES (?, ?, 1, ?, ?, ?)`,
			i, i, weekStart, weekEnd, fmt.Sprintf("Week %d", i))
	}

	exec(`INSERT INTO leagues (id, name, type, year, region) VALUES (1, 'Test League', 'Parks', 2026, 'Brighton')`)
	exec(`INSERT INTO divisions (id, name, level, play_day, league_id, season_id) VALUES (1, 'Division 1', 1, 'Tuesday', 1, 1)`)
	exec(`INSERT INTO clubs (id, name) VALUES (1, 'St Ann''s'), (2, 'Rivals')`)
	// Three home-club teams so the target team (rank 2) is neither top nor lowest
	exec(`INSERT INTO teams (id, name, club_id, division_id, season_id) VALUES
		(1, 'St Ann''s',   1, 1, 1),
		(2, 'St Ann''s B', 1, 1, 1),
		(3, 'St Ann''s C', 1, 1, 1),
		(4, 'Rivals',      2, 1, 1),
		(5, 'Rivals B',    2, 1, 1)`)
	exec(`INSERT INTO players (id, first_name, last_name, club_id) VALUES ('p1', 'Test', 'Player', 1)`)

	// Real fixture calendar: league week N is played on the Tuesday N-1 weeks
	// after the season start (week 10 = Jun 16, well before its drifted
	// window which starts Jul 7).
	fixtureDate := func(weekNumber int) time.Time {
		return seasonStart.AddDate(0, 0, (weekNumber-1)*7)
	}

	// Seed a fixture for the top team with the player in a matchup (a match
	// "played up"), returning nothing; fixture id = 100+week for readability.
	playedUp := func(weekNumber int) {
		t.Helper()
		fixtureID := 100 + weekNumber
		matchupID := 100 + weekNumber
		exec(`INSERT INTO fixtures (id, home_team_id, away_team_id, division_id, season_id, week_id, scheduled_date, venue_location, status, notes)
			VALUES (?, 1, 4, 1, 1, ?, ?, '', 'Completed', '')`, fixtureID, weekNumber, fixtureDate(weekNumber))
		exec(`INSERT INTO matchups (id, fixture_id, type, status) VALUES (?, ?, 'Mens', 'Finished')`, matchupID, fixtureID)
		exec(`INSERT INTO matchup_players (matchup_id, player_id, is_home) VALUES (?, 'p1', 1)`, matchupID)
	}

	// Target fixture: the lower team (St Ann's B) plays in league week 15
	const targetFixtureID = 500
	exec(`INSERT INTO fixtures (id, home_team_id, away_team_id, division_id, season_id, week_id, scheduled_date, venue_location, status, notes)
		VALUES (?, 2, 5, 1, 1, 15, ?, '', 'Scheduled', '')`, targetFixtureID, fixtureDate(15))

	// A first-half fixture for the lower team (league week 9)
	const firstHalfFixtureID = 501
	exec(`INSERT INTO fixtures (id, home_team_id, away_team_id, division_id, season_id, week_id, scheduled_date, venue_location, status, notes)
		VALUES (?, 2, 5, 1, 1, 9, ?, '', 'Completed', '')`, firstHalfFixtureID, fixtureDate(9))

	svc := NewService(db, "", 1, "")
	elig := svc.teamEligibilityService

	check := func(name string, fixtureID uint, want PlayerEligibilityInfo) {
		t.Helper()
		got, err := elig.GetPlayerEligibilityForTeam(ctx, "p1", 2, fixtureID)
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if got.CanPlay != want.CanPlay || got.IsLockedToHigherTeam != want.IsLockedToHigherTeam ||
			got.RemainingHigherTeamPlays != want.RemainingHigherTeamPlays || got.NeedsWarning != want.NeedsWarning {
			t.Errorf("%s: got {CanPlay:%v LockedHigher:%v Remaining:%d Warning:%v}, want {CanPlay:%v LockedHigher:%v Remaining:%d Warning:%v}",
				name,
				got.CanPlay, got.IsLockedToHigherTeam, got.RemainingHigherTeamPlays, got.NeedsWarning,
				want.CanPlay, want.IsLockedToHigherTeam, want.RemainingHigherTeamPlays, want.NeedsWarning)
		}
	}

	// Three matches played up in league weeks 10-12: all dated before the
	// drifted week-10 window start (Jul 7), so a date-based count would miss
	// every one of them and report "4 left".
	playedUp(10)
	playedUp(11)
	playedUp(12)
	check("3 played up, week-15 fixture", targetFixtureID,
		PlayerEligibilityInfo{CanPlay: true, RemainingHigherTeamPlays: 1, NeedsWarning: true})

	// First-half fixtures are unrestricted regardless of matches played up
	check("first-half fixture unrestricted", firstHalfFixtureID,
		PlayerEligibilityInfo{CanPlay: true, RemainingHigherTeamPlays: -1})

	// Fourth match played up: at the Rule 16 limit but still eligible
	playedUp(13)
	check("4 played up, at limit but eligible", targetFixtureID,
		PlayerEligibilityInfo{CanPlay: true, RemainingHigherTeamPlays: 0, NeedsWarning: true})

	// Being selected into the target fixture itself must not affect the count
	exec(`INSERT INTO matchups (id, fixture_id, type, status) VALUES (500, ?, 'Mens', 'Pending')`, targetFixtureID)
	exec(`INSERT INTO matchup_players (matchup_id, player_id, is_home) VALUES (500, 'p1', 1)`)
	check("selection into target fixture not counted", targetFixtureID,
		PlayerEligibilityInfo{CanPlay: true, RemainingHigherTeamPlays: 0, NeedsWarning: true})
	exec(`DELETE FROM matchup_players WHERE matchup_id = 500`)

	// Fifth match played up: more than four, locked to the higher team
	playedUp(14)
	check("5 played up, locked to higher team", targetFixtureID,
		PlayerEligibilityInfo{CanPlay: false, IsLockedToHigherTeam: true, RemainingHigherTeamPlays: -1})

	got, err := elig.GetPlayerEligibilityForTeam(ctx, "p1", 2, targetFixtureID)
	if err != nil {
		t.Fatalf("locked lookup: %v", err)
	}
	if got.LockedToTeamName != "St Ann's" {
		t.Errorf("LockedToTeamName = %q, want %q", got.LockedToTeamName, "St Ann's")
	}
}

// findMigrationsPathAdmin walks up from the package directory to locate the
// project's migrations directory.
func findMigrationsPathAdmin(t *testing.T) string {
	t.Helper()
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	dir := cwd
	for i := 0; i < 6; i++ {
		candidate := filepath.Join(dir, "migrations")
		if info, err := os.Stat(candidate); err == nil && info.IsDir() {
			return candidate
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	t.Fatalf("could not locate migrations directory from %s", cwd)
	return ""
}
